// HivewireErrors.h -- Hivewire's error codes and the recorder that raises them.
//
// GENERATED by tools/gen_errors.py from errors/codes.json. Edit the JSON and
// regenerate; do not edit this file. What each code means: ERRORS.md.
//
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include <Arduino.h>
#include <stdarg.h>
#include "Hivewire.h"

enum HwErrCode : uint16_t {
  HW_E_NONE = 0,
  HW_E_RADIO_DEAF = 101,               // Radio heard no Wi-Fi networks at boot
  HW_E_RADIO_START_FAILED = 102,       // ESP-NOW failed to start
  HW_E_NO_COORDINATOR = 103,           // No beacon from the coordinator for the failsafe period
  HW_E_WEAK_LINK = 104,                // Link weaker than -90 dBm
  HW_E_FW_CRC_BAD = 201,               // Firmware image refused: checksum mismatch
  HW_E_FW_TRANSFER_STALLED = 202,      // Firmware transfer stalled and was abandoned
  HW_E_FW_WRONG_FAMILY = 203,          // Firmware image for a different node type, refused
  HW_E_FW_NO_SPACE = 204,              // Firmware image too large for the update partition
  HW_E_FW_WRITE_FAILED = 205,          // Firmware image could not be written or finalised
  HW_E_UPDATE_ROLLED_BACK = 206,       // New firmware did not rejoin the swarm and was rolled back
  HW_E_OTA_WIFI_FAILED = 207,          // Over-the-air Wi-Fi update could not complete
  HW_E_PERIPHERAL_MISSING = 301,       // A peripheral did not answer
  HW_E_PERIPHERAL_READ_FAILED = 302,   // A peripheral stopped answering
  HW_E_INPUT_FLOATING = 303,           // An input looks unconnected
  HW_E_VALUE_OUT_OF_RANGE = 304,       // A reading is outside its plausible range
  HW_E_BATTERY_LOW = 305,              // Battery low
  HW_E_UNASSIGNED = 401,               // Board has no node number yet
  HW_E_BAD_NODE_ID = 402,              // Node number rejected
  HW_E_UPLINK_DOWN = 501,              // Gateway lost an uplink
  HW_E_UNTRUSTED_COMMAND = 502,        // Command from an untrusted source refused
  HW_E_GATEWAY_SILENT = 601,           // Gateway not answering on USB
  HW_E_CLOCK_BEHIND = 602,             // Host clock is behind, readings held
  HW_E_UPLOAD_FAILED = 603,            // Upload to an external service failed
  HW_E_FLASH_FAILED = 604,             // Flashing a board failed
  HW_E_HOST_UNDERVOLTAGE = 605,        // Host power supply is too weak
  HW_E_WRITE_NOT_APPLIED = 606,        // A setting was sent but the node never confirmed it
};

// ---------------------------------------------------------------------------
// Raising a code
// ---------------------------------------------------------------------------
// A node keeps the most recent error and a count since boot, and publishes
// them in two slots by convention (see HW_ERR_SLOT_*), so the host sees them
// on its normal poll without asking. Each raise also goes into the node's log
// as "E<code>/<subject> <detail>", which is what `log <id>` fetches.
//
// `subject` says WHICH thing the code is about, so one generic code serves any
// application: for a peripheral code it is the slot id the device feeds; for
// an uplink code, the uplink's index; 0 when there is nothing more specific.
//
// Codes 1000-1999 are the application's own (HW_E_APP_FIRST..LAST). The
// library never uses them; describe them in the node type's kinds.json entry
// so the admin can explain them.

#define HW_E_APP_FIRST 1000
#define HW_E_APP_LAST  1999

// Slot ids the bundled sketches use for the error pair. Applications that
// raise codes should publish these too, with the samplers below.
#define HW_ERR_SLOT_LAST  26   // HW_U32: code | subject << 16
#define HW_ERR_SLOT_COUNT 27   // HW_U16: errors raised since boot

struct HwErrState {
  uint16_t code = 0;        // most recent, 0 = none since boot
  uint8_t  subject = 0;
  uint16_t count = 0;       // since boot, saturating
  uint32_t atMs = 0;        // millis() when it was raised
};

inline HwErrState &hwErrState() {
  static HwErrState s;
  return s;
}

// Record an error. Safe before node.begin(): the log line is skipped until the
// node has an id, but the slots still carry the code once the node joins.
inline void hwErr(HivewireNode &node, uint16_t code, uint8_t subject = 0,
                  const char *fmt = nullptr, ...) {
  HwErrState &s = hwErrState();
  s.code = code;
  s.subject = subject;
  if (s.count < 0xFFFF) s.count++;
  s.atMs = millis();
  char detail[40] = "";
  if (fmt) {
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(detail, sizeof(detail), fmt, ap);
    va_end(ap);
  }
  if (node.id()) {
    if (subject) node.log("E%u/%u %s", code, subject, detail);
    else         node.log("E%u %s", code, detail);
  }
}

// Samplers for the two error slots:
//   { HW_ERR_SLOT_LAST,  HW_U32, HW_DIR_OUT, 30000, 900000, 1, 0, 0, hwErrSlotLast,  nullptr },
//   { HW_ERR_SLOT_COUNT, HW_U16, HW_DIR_OUT, 30000, 900000, 1, 0, 0, hwErrSlotCount, nullptr },
inline void hwErrSlotLast(void *out) {
  const HwErrState &s = hwErrState();
  uint32_t v = (uint32_t)s.code | ((uint32_t)s.subject << 16);
  memcpy(out, &v, 4);
}
inline void hwErrSlotCount(void *out) {
  uint16_t v = hwErrState().count;
  memcpy(out, &v, 2);
}

// Raise WEAK_LINK when the last packet heard was weaker than `dbm`, at most
// once per `everyMs` -- a node at the edge of range would otherwise raise it
// on every beacon. Call from loop().
inline void hwErrCheckLink(HivewireNode &node, int8_t dbm = -90,
                           uint32_t everyMs = 30UL * 60 * 1000) {
  static uint32_t last = 0;
  int8_t r = node.lastRssi();
  if (r == 0 || r >= dbm) return;              // 0 = nothing heard yet
  if (last && millis() - last < everyMs) return;
  last = millis();
  hwErr(node, HW_E_WEAK_LINK, 0, "weak link %d dBm", r);
}
